# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MODEL_Identify Bluespot Fill Up Values NoBuildings.py
# Created on: 2015-12-06 23:13:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: MODEL_Identify Bluespot Fill Up Values NoBuildings <Output_Workspace> <DEM> <Vertical_accuracy__meters_> 
# Description: 
# This model derives bluespots from a DEM. Bluespots are natural landscape depressions vulnerable to flooding during extreme rainfall events. The model analyzes the amount of water that is needed to fill each blue spot, thus making it possible to assign relative degrees of flood risk.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Output_Workspace = arcpy.GetParameterAsText(0)
if Output_Workspace == '#' or not Output_Workspace:
    Output_Workspace = "C:\\Application\\Xien_1113\\Cloudburst\\Cloudburst\\Outputs_BluespotsFillUp.gdb" # provide a default value if unspecified

DEM = arcpy.GetParameterAsText(1)
if DEM == '#' or not DEM:
    DEM = "C:\\Application\\Xien_1113\\Cloudburst\\Cloudburst\\Inputs.gdb\\DEM" # provide a default value if unspecified

Vertical_accuracy__meters_ = arcpy.GetParameterAsText(2)
if Vertical_accuracy__meters_ == '#' or not Vertical_accuracy__meters_:
    Vertical_accuracy__meters_ = "0.05" # provide a default value if unspecified

# Local variables:
Small_Sinks_Filled = "%Output Workspace%\\SmallSinksFilled"
Optional_raster = ""
All_Sinks_Filled = "%Output Workspace%\\AllSinksFilled"
Bluespot_Depths_Cell_by_Cell = "%Output Workspace%\\BSDepths"
v1 = "1"
Preliminary_Bluespots = "%Output Workspace%\\PreliminaryBS"
Bluespot_Regions = "%Output Workspace%\\BSRegions"
Bluespots___Volume_Field = Bluespot_Regions
Join_Unfilled_Depths = Bluespots___Volume_Field
Sum_Unfilled_Depths = "%Output Workspace%\\UnfilledDepth"
Join_Filled_Depths = Join_Unfilled_Depths
Sum_Filled_Depths = "%Output Workspace%\\FilledDepth"
Bluespot_Volumes = Join_Filled_Depths
CellSize = "1.6"
Joined_Watershed_Areas = Bluespot_Volumes
Flow_Direction_Raster = "%Output Workspace%\\FlowDirection"
Watersheds = "%Output Workspace%\\Watersheds"
Watersheds___Attribute_Table = Watersheds
Watersheds___Area_Field = Watersheds___Attribute_Table
Watershed_Areas = Watersheds___Area_Field
Bluespots___FillUp_Field = Joined_Watershed_Areas
Bluespot_Fill_Up_Values = Bluespots___FillUp_Field
Bluespots = Bluespot_Fill_Up_Values
Bluespot_Polygons = "%Output Workspace%\\BSPoly"
Bluespot_Polygons_with_IDs = "%Output Workspace%\\BSPolyDissolved"

# Set Geoprocessing environments
arcpy.env.outputCoordinateSystem = ""
arcpy.env.snapRaster = DEM
arcpy.env.extent = DEM
arcpy.env.cellSize = "1.6"
arcpy.env.geographicTransformations = ""
arcpy.env.mask = ""

# Process: Fill
arcpy.gp.Fill_sa(DEM, Small_Sinks_Filled, Vertical_accuracy__meters_)

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(Small_Sinks_Filled, Flow_Direction_Raster, "NORMAL", Optional_raster)

# Process: Fill (2)
arcpy.gp.Fill_sa(DEM, All_Sinks_Filled, "")

# Process: Minus
arcpy.gp.Minus_sa(All_Sinks_Filled, Small_Sinks_Filled, Bluespot_Depths_Cell_by_Cell)

# Process: Con
arcpy.gp.Con_sa(Bluespot_Depths_Cell_by_Cell, v1, Preliminary_Bluespots, "", "Value > 0")

# Process: Region Group
arcpy.gp.RegionGroup_sa(Preliminary_Bluespots, Bluespot_Regions, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Add Field
arcpy.AddField_management(Bluespot_Regions, "Volume", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(Bluespot_Regions, "VALUE", Small_Sinks_Filled, Sum_Unfilled_Depths, "DATA", "SUM")

# Process: Join Field
arcpy.JoinField_management(Bluespots___Volume_Field, "Value", Sum_Unfilled_Depths, "Value", "SUM")

# Process: Zonal Statistics as Table (2)
arcpy.gp.ZonalStatisticsAsTable_sa(Bluespot_Regions, "VALUE", All_Sinks_Filled, Sum_Filled_Depths, "DATA", "SUM")

# Process: Join Field (2)
arcpy.JoinField_management(Join_Unfilled_Depths, "Value", Sum_Filled_Depths, "Value", "SUM")

# Process: Get Raster Properties
arcpy.GetRasterProperties_management(Bluespot_Regions, "CELLSIZEX", "")

# Process: Calculate Field
arcpy.CalculateField_management(Join_Filled_Depths, "Volume", "%CellSize% * %CellSize% * (!SUM_1! - !SUM!)", "PYTHON_9.3", "")

# Process: Watershed
arcpy.gp.Watershed_sa(Flow_Direction_Raster, Bluespot_Regions, Watersheds, "VALUE")

# Process: Build Raster Attribute Table
arcpy.BuildRasterAttributeTable_management(Watersheds, "NONE")

# Process: Add Field (2)
arcpy.AddField_management(Watersheds___Attribute_Table, "WatshdArea", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Watersheds___Area_Field, "WatshdArea", "%CellSize% * %CellSize% * !Count!", "PYTHON_9.3", "")

# Process: Join Field (3)
arcpy.JoinField_management(Bluespot_Volumes, "Value", Watershed_Areas, "Value", "WatshdArea")

# Process: Add Field (3)
arcpy.AddField_management(Joined_Watershed_Areas, "FillUp", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Bluespots___FillUp_Field, "FillUp", "!Volume! * 1000 / !WatshdArea!", "PYTHON_9.3", "")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(Bluespot_Fill_Up_Values, Bluespot_Polygons, "NO_SIMPLIFY", "VALUE")

# Process: Dissolve
arcpy.Dissolve_management(Bluespot_Polygons, Bluespot_Polygons_with_IDs, "gridcode", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Join Field (4)
arcpy.JoinField_management(Bluespot_Polygons_with_IDs, "gridcode", Bluespot_Fill_Up_Values, "Value", "Volume;FillUp")

